version: '3.8'

services:
  webapp:
    build: .
    container_name: personal-task-app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
